---

- name: golang installed check
  stat: path=/usr/local/go
  register: golang_path

- name: download golang binary
  get_url:
    url=https://storage.googleapis.com/golang/go{{ golang_version }}.linux-amd64.tar.gz
    dest=/tmp/go{{ golang_version }}.linux-amd64.tar.gz
    mode=0440
  when: not golang_path.stat.exists

- name: unarchive golang
  shell: tar -C /usr/local -xzf /tmp/go{{ golang_version }}.linux-amd64.tar.gz
  when: not golang_path.stat.exists

- name: add golang path to environment
  lineinfile:
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?/usr/local/go/bin).*?)(["]*)$'
    line="PATH=\1\2:/usr/local/go/bin\3"