---

- name: golang installed check
  stat: path=/usr/local/go
  register: golang_path

- name: download golang binary
  get_url:
    url=https://storage.googleapis.com/golang/go{{ golang_version }}.linux-amd64.tar.gz
    dest=/tmp/go{{ golang_version }}.linux-amd64.tar.gz
    mode=0440
  when: not golang_path.stat.exists

- name: unarchive golang
  shell: tar -C /usr/local -xzf /tmp/go{{ golang_version }}.linux-amd64.tar.gz
  when: not golang_path.stat.exists

- name: add golang path to environment via a profile.d entry
  copy:
    src=golang.sh
    dest=/etc/profile.d

- name: ensure the golang profile.d entry is executable
  file: path=/etc/profile.d/golang.sh mode="a+x"

- name: symlink go binaries to /usr/local/bin
  file: src=/usr/local/go/bin/{{ item }} dest=/usr/local/bin/{{ item }} state=link
  with_items:
    - go
    - godoc
    - gofmt